# This file allows for setting specific changes to the Single Student View
# File, although it is less customizable through yaml than the other files
#
# This entire file allows for customization of both the Excel and the PDF
# versions of the single student per page report
#
# Most of the Excel information is at the beginning and most of the PDF
# info is at the end

# This allows individual campuses to customize the header at the top of the page
counselor_header:
    Standard: '="Cnslr: "&INDEX(Counselor,MATCH(D3,KidIDs,0))'
    Golder: '="Cnslr: "&INDEX(Counselor,MATCH(D3,KidIDs,0))&" ("&INDEX(Cohort,MATCH(D3,KidIDs,0))&")"'
    #Standard: '="Advisor: "&INDEX(Advisors,MATCH(D3,KidIDs,0))'
    Comer: '="Cnslr: "&INDEX(Counselor,MATCH(D3,KidIDs,0))&" ("&INDEX(Cohort,MATCH(D3,KidIDs,0))&")"&", Advr: "&INDEX(Advisors,MATCH(D3,KidIDs,0))'
    Noble: '="Cnslr: "&INDEX(Counselor,MATCH(D3,KidIDs,0))&", Advr: "&INDEX(Advisors,MATCH(D3,KidIDs,0))'
    Muchin: '="Cnslr: "&INDEX(Counselor,MATCH(D3,KidIDs,0))&", Advr: "&INDEX(Advisors,MATCH(D3,KidIDs,0))'
    UIC: '="Cnslr: "&INDEX(Counselor,MATCH(D3,KidIDs,0))&" ("&INDEX(Cohort,MATCH(D3,KidIDs,0))&")"&", Advr: "&INDEX(Advisors,MATCH(D3,KidIDs,0))'
    RoweClark: '="Cnslr: "&INDEX(Counselor,MATCH(D3,KidIDs,0))&", Advr: "&INDEX(Advisors,MATCH(D3,KidIDs,0))'
    Bulls: '=INDEX(Counselor,MATCH(D3,KidIDs,0))&" ("&INDEX(Cohort,MATCH(D3,KidIDs,0))&"), "&INDEX(Advisors,MATCH(D3,KidIDs,0))'
    Rauner: '="Cnslr: "&INDEX(Counselor,MATCH(D3,KidIDs,0))&" ("&INDEX(Cohort,MATCH(D3,KidIDs,0))&")"'
    Johnson: '="("&TEXT(TODAY(),"m/d")&"): "&INDEX(Counselor,MATCH(D3,KidIDs,0))&" ("&INDEX(Cohort,MATCH(D3,KidIDs,0))&")"'
    PAS: '="Campus: "&INDEX(Campus,MATCH(D3,KidIDs,0))'

print_header: # non-standard note on F1 about the print date or other
    Pritzker: '="EFC: "&INDEX(EFC,MATCH(D3,KidIDs,0))'
    Rauner: '="Strategy "&INDEX(Strats,MATCH(D3,KidIDs,0))'
    RoweClark: '="("&INDEX(Cohort,MATCH(D3,KidIDs,0))&")"'
    Standard: ''

print_footer: # non-standard text in E37 with a bar across E:J
    Johnson: '="Advisor: "&INDEX(Advisors,MATCH(D3,KidIDs,0))'
    Rauner: '="Printed on: "&TEXT(TODAY(),"mm/dd")'
    Noble: '="EFC: "&INDEX(EFC,MATCH(D3,KidIDs,0))&"; Printed on: "&TEXT(TODAY(),"mm/dd")'
    #Standard: '="Advisor: "&INDEX(Advisors,MATCH(D3,KidIDs,0))'
    Standard: ''

# This tells the row index (0 reference) for each section
row_info:
    Blank:
        blank_start: 8
        blank_end: 45
        student_start: 0
        student_end: 0
    Standard:
        blank_start: 8 #start of data row
        blank_end: 10
        student_start: 12 #start of data row
        student_end: 36
    ComerOld:
        blank_start: 8
        blank_end: 10
        student_start: 12
        student_end: 31
        aspect: landscape


# Generic descriptions of goals come first and then school specific ones
goal_descriptions:
    total:
        Descr: 'Total applications'
        Label: '="@+ total applications"'
        Eval: '=INDEX(Apps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    lt_total:
        Descr: 'Maximum number of total applications'
        Label: '="@- total applications"'
        Eval: '=INDEX(Apps,MATCH(D3,KidIDs,0))'
        Sign: '<='
    reach:
        Descr: 'Schools with Reach Odds'
        Label: '="@+ "&LOWER(ReachLabel)&" schools"'
        Eval: '=INDEX(ReachApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    money_reach:
        Descr: 'Money schools with Reach Odds'
        Label: '="@+ money "&LOWER(ReachLabel)&" schools"'
        Eval: '=INDEX(MoneyReachApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    match:
        Descr: 'Schools with Match Odds'
        Label: '="@+ "&LOWER(MatchLabel)&" schools"'
        Eval: '=INDEX(MatchApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    money_match:
        Descr: 'Money schools with Match Odds'
        Label: '="@+ money "&LOWER(MatchLabel)&" schools"'
        Eval: '=INDEX(MoneyMatchApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    match_plus:
        Descr: 'Schools with Match or better Odds'
        Label: '="@+ "&LOWER(MatchLabel)&" or better (50%+ odds)"'
        Eval: '=INDEX(MatchOrUnderApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    safety:
        Descr: 'Schools with Safety, Secure, or Sure Thing Odds'
        Label: '="@+ "&LOWER(SafetyLabel)&" schools"'
        Eval: '=INDEX(SafetyApps,MATCH(D3,KidIDs,0))+INDEX(SecureApps,MATCH(D3,KidIDs,0))+INDEX(SureThingApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    safety_no_goal:
        Descr: 'Schools with Safety, Secure, or Sure Thing Odds'
        Label: '=LOWER(SafetyLabel)&" schools"'
        Eval: '=INDEX(SafetyApps,MATCH(D3,KidIDs,0))+INDEX(SecureApps,MATCH(D3,KidIDs,0))+INDEX(SureThingApps,MATCH(D3,KidIDs,0))'
        Sign: 'N/A'
    lt_safety:
        Descr: 'Maximum number of schools with Safety, Secure, or Sure Thing Odds'
        Label: '="@- "&LOWER(SafetyLabel)&" schools"'
        Eval: '=INDEX(SafetyApps,MATCH(D3,KidIDs,0))+INDEX(SecureApps,MATCH(D3,KidIDs,0))+INDEX(SureThingApps,MATCH(D3,KidIDs,0))'
        Sign: '<='
    lt_longshot_under:
        Descr: 'Maximum number of apps with Longshot or worse odds'
        Label: '="@- """&LOWER(HailMaryLabel)&""" or """&LOWER(LongshotLabel)&""""'
        Eval: '=INDEX(HailMaryApps,MATCH(D3,KidIDs,0))+INDEX(LongshotApps,MATCH(D3,KidIDs,0))'
        Sign: '<='
    lt_bad_money:
        Descr: 'Maximum number of apps with ---, --, +/--, or +/--- money codes'
        Label: '="@- ""bad"" money options"'
        Eval: '=INDEX(BadMoneyApps,MATCH(D3,KidIDs,0))'
        Sign: '<='
    money_safety:
        Descr: 'Any money school with Safety, Secure, or Sure Thing Odds'
        Label: '="@+ money "&LOWER(SafetyLabel)&" schools"'
        Eval: '=INDEX(MoneySafetyApps,MATCH(D3,KidIDs,0))+INDEX(MoneySecureApps,MATCH(D3,KidIDs,0))+INDEX(MoneySureThingApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    lt_far_below_tgr:
        Descr: 'Maximum number of schools with grad rate 10% or more below Target'
        Label: '="@- "&LOWER(FarBelowTGRLabel)&" grad rate schools"'
        Eval: '=INDEX(FarBelowTGRApps,MATCH(D3,KidIDs,0))'
        Sign: '<='
    tgr_only:
        Descr: 'Schools with Grad Rate at or above Target, but below Ideal'
        Label: '="@+ "&LOWER(TargetGRLabel)&" grad rate schools"'
        Eval: '=AD6-AE6'
        Sign: '>='
    tgr_plus:
        Descr: 'Schools with Grad Rate at or above Target'
        Label: '="@+ "&LOWER(TargetGRLabel)&" grad rate or better schools"'
        Eval: '=INDEX(TGRorBetterApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    tgr_plus_no_goal:
        Descr: 'Schools with Grad Rate at or above Target'
        Label: '=LOWER(TargetGRLabel)&" grad rate or better schools"'
        Eval: '=INDEX(TGRorBetterApps,MATCH(D3,KidIDs,0))'
        Sign: 'N/A'
    money_tgr_plus:
        Descr: 'Schools with Grad Rate at or above Target, also money'
        Label: '="@+ money "&LOWER(TargetGRLabel)&" grad rate schools"'
        Eval: '=INDEX(MoneyMGRPlus,MATCH(D3,KidIDs,0))'
        Sign: '>='
    money_tgr_only_reach_plus:
        Descr: 'Schools with Grad Rate at or above Target, but below Ideal, also money, also 20+% odds'
        Label: '="@+ money "&LOWER(TargetGRLabel)&" grad rate schools"'
        Eval: '=INDEX(MoneyMGROdds,MATCH(D3,KidIDs,0))'
        Sign: '>='
    money_tgr_only_longshot_plus:
        Descr: 'Schools with Grad Rate at or above Target, but below Ideal, also money, also 10+% odds'
        Label: '="@+ money "&LOWER(TargetGRLabel)&" grad rate schools"'
        Eval: '=INDEX(MoneyMGROddsLongshot,MATCH(D3,KidIDs,0))'
        Sign: '>='
    igr:
        Descr: 'Schools with Grad Rate at or above Ideal'
        Label: '="@+ "&LOWER(IdealGRLabel)&" grad rate schools"'
        Eval: '=AE6'
        Sign: '>='
    money_tgr_plus_match_plus:
        Descr: 'Schools with Grad Rate at or above Target, also money, also 50+% odds'
        Label: '="@+ money "&LOWER(TargetGRLabel)&" grad rate, w 50+% odds"'
        Eval: '=INDEX(MoneyMGRPlusMatch,MATCH(D3,KidIDs,0))'
        Sign: '>='
    money_igr_reach_plus:
        Descr: 'Schools with Grad Rate at or above Ideal, also money, also 20+% odds'
        Label: '="@+ money "&LOWER(IdealGRLabel)&" grad rate schools"'
        Eval: '=INDEX(MoneyRGROdds,MATCH(D3,KidIDs,0))'
        Sign: '>='
    money_igr_longshot_plus:
        Descr: 'Schools with Grad Rate at or above Ideal, also money, also 10+% odds'
        Label: '="@+ money "&LOWER(IdealGRLabel)&" grad rate schools"'
        Eval: '=INDEX(MoneyRGROddsLongshot,MATCH(D3,KidIDs,0))'
        Sign: '>='
    il_public:
        Descr: 'Illinois Public Schools'
        Label: '="@+ Illinois public schools"'
        Eval: '=INDEX(ILPubApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    il_public_no_goal:
        Descr: 'Illinois Public Schools'
        Label: '="Illinois public schools"'
        Eval: '=INDEX(ILPubApps,MATCH(D3,KidIDs,0))'
        Sign: 'N/A'
    il_match_plus:
        Descr: 'Illinois Public with 50+% odds, also money'
        Label: '="@+ Illinois match, safety, or secure"'
        Eval: '=INDEX(ILPubMSS,MATCH(D3,KidIDs,0))'
        Sign: '>='
    money:
        Descr: 'Schools that are money based on the +/- code'
        Label: '="@+ money options (++/-, ++, or +++)"'
        Eval: '=INDEX(AllMoneyApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    money_no_goal:
        Descr: 'Schools that are money based on the +/- code'
        Label: '="money options (++/-, ++, or +++)"'
        Eval: '=INDEX(AllMoneyApps,MATCH(D3,KidIDs,0))'
        Sign: 'N/A'
    money_chicago:
        Descr: 'Money schools in the Chicago commute radius'
        Label: '="@+ money Chicagoland schools"'
        Eval: '=INDEX(MoneyChicagoApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    golden_three:
        Descr: 'Schools with grad rate at or above target, are money, and have 50+% odds'
        Label: '="@+ meeting all 3 of the above"'
        Eval: '=INDEX(GoldenThreeApps,MATCH(D3,KidIDs,0))'
        Sign: '>='
    national_louis:
        Descr: 'An application to National-Louis University'
        Label: '="@ app to National-Louis University"'
        Eval: '=INDEX(NLUApps,MATCH(D3,KidIds,0))'
        Sign: '>='
    city_college:
        Descr: 'An application to City Colleges of Chicago'
        Label: '="@ app to City Colleges"'
        Eval: '=INDEX(CityCollegesApps,MATCH(D3,KidIds,0))'
        Sign: '>='
        
school_goals:
    UIC:
        - money_tgr_plus: '[(8,2),(5,3),4]'
        - igr: '[(8,0),2]'
        - money: '[(8,3),(5,4),6]'
        - il_public: '[(8,1),2]'
    Muchin:
        - money_igr_longshot_plus: 2
        - money_tgr_only_longshot_plus: 2
        - money_safety: 2
    Rauner:
        - reach: '[(8,1),2]'
        - match: '[(8,2),3]'
        - safety: '[(8,3),4]'
        - money: 5
        - il_match_plus: 1
        - tgr_only: '[(8,4),5]'
    RoweClark:
        - money_tgr_plus: 3
        - il_public: '[(8,2),1]'
        - money_safety: '[(8,0),3]'
        - money_match: '[(8,0),3]'
        - lt_bad_money: 2
        - national_louis: '[(9,1),0]'

        - tgr_plus: 5
        - il_public: 1
    #For these lists, the structure is >=x then y, else (next...)
    # Also, a 0 means wipe out the whole goal
    Johnson:
        - money_safety: '[(8,0),3]'
        - money_match: '[(8,0),3]'
        - money_tgr_plus: 3
        - il_public: 2
    Comer:
        - money_tgr_only_longshot_plus: 3
        - igr: 2
        - tgr_only: 3
        - money_safety: 2
        - il_public: 2
    Mansueto:
        - money_safety: 3
        - money_match: 3
        - money_reach: 2
        - il_match_plus: 2
    TNA:
        - money_igr_longshot_plus: 3
        - money_tgr_only_longshot_plus: 3
        - money_match: 3
        - money_safety: 3
        - il_match_plus: 1
    Noble:
        - money_igr_longshot_plus: 2
        - money_tgr_only_longshot_plus: 2
        - il_public: 1
        - money_chicago: 1
    Golder:
        - igr: 3
        - tgr_only: 3
        - lt_far_below_tgr: 2
        - reach: 3
        - match: 3
        - lt_safety: 3
        - lt_bad_money: 2
        - lt_longshot_under: 2
    Speer:
        - money_tgr_only_longshot_plus: 3
        - money_igr_longshot_plus: 2
        - money_safety: 2
        - il_public: 1
    Pritzker:
        - money_igr_longshot_plus: 3
        - money_tgr_only_longshot_plus: 4
        - money_safety: 3
        - il_match_plus: 1
    Hansberry:
        - tgr_plus_no_goal: 1
        - money_no_goal: 1
        - safety_no_goal: 1
        - il_public_no_goal: 1
    Bulls:
        - money: 6
        - tgr_only: 3
        - igr: 2
        - il_public: 1
    Baker:
        - money_igr_longshot_plus: '[(8,2),3]'
        - money_tgr_only_longshot_plus: '[(8,2),3]'
        - money_safety: '[(8,2),3]'
        - il_public: 1
        - national_louis: '[(8,1),0]'
    DRW:
        - il_public: 2
        - tgr_plus: 3
        - money: 3
        - match_plus: 3
    Butler:
        - lt_total: '[(9,6),(5,10),12]'
        - total: '[(9,4),(5,8),10]'
        - money_safety: '[(9,0),3]'
        - money_match: '[(9,2),3]'
        - money_tgr_only_longshot_plus: '[(9,2),3]'
        - money_igr_longshot_plus: '[(5,0),2]'
        - il_public: '[(9,0),(5,2),1]'
        - national_louis: '[(9,1),0]'
    Muchin:
        - money_igr_longshot_plus: 2
        - money_tgr_only_longshot_plus: 3
        - money_safety: 3
    Rauner:
        - reach: '[(8,1),2]'
        - match: '[(8,2),3]'
        - safety: '[(8,3),4]'
        - money: 5
        - il_match_plus: 1
        - tgr_only: '[(8,4),5]'
    RoweClark:
        - money_tgr_plus: 3
        - il_public: '[(8,2),1]'
        - money_safety: '[(8,0),3]'
        - money_match: '[(8,0),3]'
        - lt_bad_money: 2
        - national_louis: '[(9,1),0]'

############################################################################
# PDF specific details start here
pdf_orientation:
    Standard: P
    Comer: P
    ComerOld: L

pdf_margins:
    top: 0.75
    left: 0.5
    right: 0.5

pdf_lines:
    thick: 0.02
    line: 0.0075

pdf_fonts:
    font_r: './fonts/Carlito-Regular.ttf'
    font_b: './fonts/Carlito-Bold.ttf'
    font_i: './fonts/Carlito-Italic.ttf'
    font_bi: './fonts/Carlito-BoldItalic.ttf'

pdf_widths:
    - 3.21 # Student name
    - 0.75 # ACT/SAT
    - 0.59 # GPA
    - 0.70 # Race/Eth
    - 0.75 # Target label
    - 1.47 # Target

pdf_heights:
    - 0.27 # Title row
    - 0.22
    - 0.21
    - 0.21
    - 0.21
    - 0.22 # end of header
    - 0.08 # small gap between header and school data
    - 0.21 # Colleges header part 1
    - 0.21 # Colleges header part 2
    - 0.21 # Height per college
    - 0.21 # Goals rows
    - 0.21 # Footer row

pdf_college_max: 25 # maximum number of colleges to list until stop

pdf_goals_start: 7.84 # location of goals box in y inches (after 25 col. rows)
pdf_footer_start: 10.00 # location of single line footer in y inches

